export const coursesData = [
  {
    id: 1,
    name: "React for Beginners",
    category: "Web Development",
    price: 2999,
    originalPrice: 2999,
    discount: 0,
    image: "https://via.placeholder.com/200",
    description:
      "Build modern, interactive user interfaces from the ground up using React, essential hooks, and component-based architecture.",
  },
  {
    id: 2,
    name: "Machine Learning with Python",
    category: "AI / ML",
    price: 2999,
    originalPrice: 2999,
    discount: 0,
    image: "https://via.placeholder.com/200",
    description:
      "Master core ML algorithms, data preprocessing, and model evaluation using Python and popular libraries like Scikit-learn and Pandas.",
  },
  {
    id: 3,
    name: "C++ & Fundamentals of DSA",
    category: "Programming",
    price: 2999,
    originalPrice: 2999,
    discount: 0,
    image: "https://via.placeholder.com/200",
    description:
      "Solidify your programming foundation by mastering essential Data Structures and Algorithms implemented efficiently in C++.",
  },
  {
    id: 4,
    name: "Machine Learning Mastery Lab",
    category: "Advanced Workshops",
    price: 2999,
    originalPrice: 2999,
    discount: 0,
    image: "https://via.placeholder.com/200",
    description:
      "A hands-on, project-based workshop designed to bridge the gap between theoretical ML knowledge and real-world deployment challenges.",
  },
  {
    id: 5,
    name: "Generative AI & Deep Learning Studio",
    category: "Advanced Workshop",
    price: 2999,
    originalPrice: 2999,
    discount: 0,
    image: "https://via.placeholder.com/200",
    description:
      "Dive into advanced neural network architectures, build foundational LLMs, and explore state-of-the-art Generative AI models.",
  },
  {
    id: 6,
    name: "Research Intern",
    category: "Internship",
    price: 2499,
    originalPrice: 2499,
    discount: 0,
    image: "https://via.placeholder.com/200",
    description:
      "A guided program offering hands-on experience in cutting-edge research methodologies, literature reviews, and scientific paper writing.",
  },
];
export const courseData = [
  {
    id: 1,
    image: 'https://placehold.co/600x400/556270/FFFFFF?text=Tech+Course',
    category: 'TECHNOLOGY',
    instructor: 'Colene Landin',
    title: 'Artificial intelligence and machine learning foundations',
    oldPrice: '50.00',
    newPrice: '45.00',
  },
  {
    id: 2,
    image: 'https://placehold.co/600x400/4ECDC4/FFFFFF?text=Math+Course',
    category: 'MATHEMATICS',
    instructor: 'Colene Landin',
    title: 'Essential math skills for data science and analysis',
    oldPrice: '50.00',
    newPrice: '45.00',
  },
  {
    id: 3,
    image: 'https://placehold.co/600x400/C7F464/333333?text=Business+Course',
    category: 'BUSINESS',
    instructor: 'Colene Landin',
    title: 'Effective communication and public speaking skills',
    oldPrice: '50.00',
    newPrice: '49.00',
  },
  {
    id: 4,
    image: 'https://placehold.co/600x400/FF6B6B/FFFFFF?text=Design+Course',
    category: 'DESIGN',
    instructor: 'John Doe',
    title: 'UI/UX Design Principles for Beginners',
    oldPrice: '60.00',
    newPrice: '89.99',
  },
  {
    id: 5,
    image: 'https://placehold.co/600x400/C44D58/FFFFFF?text=Marketing+Course',
    category: 'MARKETING',
    instructor: 'Jane Smith',
    title: 'Digital Marketing & SEO Fundamentals',
    oldPrice: '50.00',
    newPrice: '45.00',
  },
  {
    id: 6,
    image: 'https://placehold.co/600x400/34314C/FFFFFF?text=Finance+Course',
    category: 'FINANCE',
    instructor: 'Adam Beck',
    title: 'Personal Finance and Investment Strategy',
    oldPrice: '70.00',
    newPrice: '55.00',
  },
];