export const coursesData = [
  {
    id: 1,
    name: "React for Beginners",
    category: "Web Development",
    price: 499,
    originalPrice: 999,
    discount: 50,
    image: "https://via.placeholder.com/200",
    description:
      "Learn React from scratch with practical examples and projects.",
  },
  {
    id: 2,
    name: "Machine Learning with Python",
    category: "AI / ML",
    price: 699,
    originalPrice: 1399,
    discount: 50,
    image: "https://via.placeholder.com/200",
    description:
      "Master ML fundamentals and build predictive models using Python.",
  },
  {
    id: 3,
    name: "Data Structures in C",
    category: "Programming",
    price: 299,
    originalPrice: 599,
    discount: 50,
    image: "https://via.placeholder.com/200",
    description:
      "Understand data structures with in-depth examples in C language.",
  },
];
export const courseData = [
  {
    id: 1,
    image: 'https://placehold.co/600x400/556270/FFFFFF?text=Tech+Course',
    category: 'TECHNOLOGY',
    instructor: 'Colene Landin',
    title: 'Artificial intelligence and machine learning foundations',
    oldPrice: '50.00',
    newPrice: '45.00',
  },
  {
    id: 2,
    image: 'https://placehold.co/600x400/4ECDC4/FFFFFF?text=Math+Course',
    category: 'MATHEMATICS',
    instructor: 'Colene Landin',
    title: 'Essential math skills for data science and analysis',
    oldPrice: '50.00',
    newPrice: '45.00',
  },
  {
    id: 3,
    image: 'https://placehold.co/600x400/C7F464/333333?text=Business+Course',
    category: 'BUSINESS',
    instructor: 'Colene Landin',
    title: 'Effective communication and public speaking skills',
    oldPrice: '50.00',
    newPrice: '45.00',
  },
  {
    id: 4,
    image: 'https://placehold.co/600x400/FF6B6B/FFFFFF?text=Design+Course',
    category: 'DESIGN',
    instructor: 'John Doe',
    title: 'UI/UX Design Principles for Beginners',
    oldPrice: '60.00',
    newPrice: '49.99',
  },
  {
    id: 5,
    image: 'https://placehold.co/600x400/C44D58/FFFFFF?text=Marketing+Course',
    category: 'MARKETING',
    instructor: 'Jane Smith',
    title: 'Digital Marketing & SEO Fundamentals',
    oldPrice: '50.00',
    newPrice: '45.00',
  },
  {
    id: 6,
    image: 'https://placehold.co/600x400/34314C/FFFFFF?text=Finance+Course',
    category: 'FINANCE',
    instructor: 'Adam Beck',
    title: 'Personal Finance and Investment Strategy',
    oldPrice: '70.00',
    newPrice: '55.00',
  },
];